from .base import *

DEBUG = False

ALLOWED_HOSTS = ENV.get('ALLOWED_HOSTS', [])

STATIC_ROOT = ENV.get('STATIC_ROOT')

STATIC_URL = ENV.get('STATIC_URL')

INSTALLED_APPS += [

]

MEDIA_ROOT = ENV.get('MEDIA_ROOT')

MEDIA_URL = ENV.get('MEDIA_URL')

CULQUI_PUBLIC_KEY_TEST = ENV.get('CULQUI_PUBLIC_KEY_TEST')
CULQUI_SECRET_KEY_TEST = ENV.get('CULQUI_SECRET_KEY_TEST')
