# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customershippingaddress'),
        ('product', '0013_auto_20180227_1917'),
        ('cart', '0002_auto_20180227_1917'),
        ('ubigeo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_trash', models.BooleanField(default=False, verbose_name='is trash')),
                ('code', models.CharField(max_length=255, unique=True, verbose_name='code')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='sub total')),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Envio')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='total')),
                ('type_status', models.CharField(blank=True, choices=[('PG', 'Pagado'), ('DN', 'Denegado'), ('RC', 'Rechazado'), ('PE', 'Pendiente'), ('DES', 'En Despacho'), ('CAM', 'En Camino'), ('COM', 'Completado'), ('CN', 'Cancelado')], max_length=255, verbose_name='type_status')),
                ('is_send_email', models.BooleanField(default=False)),
                ('is_return_stock', models.BooleanField(default=False)),
                ('cart', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_order', to='cart.Cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='customers.Customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Order',
            },
        ),
        migrations.CreateModel(
            name='OrderCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Apellido Paterno')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellido Materno')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=120, verbose_name='Celular')),
                ('document', models.CharField(blank=True, max_length=120, verbose_name='Documento')),
                ('type_document', models.CharField(blank=True, choices=[('DNI', 'DNI'), ('CE', 'Carnet de extranjería')], max_length=120, verbose_name='Tipo Documento')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_order_customer', to='order.Order')),
            ],
            options={
                'verbose_name': 'OrderCustomer',
                'verbose_name_plural': 'OrderCustomer',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='sub_total')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_orderdetail', to='order.Order')),
                ('productdetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orderdetails', to='product.Product')),
            ],
            options={
                'verbose_name': 'OrderDetail',
                'verbose_name_plural': 'OrderDetail',
            },
        ),
        migrations.CreateModel(
            name='OrderShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Apellido Paterno')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Apellido Materno')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('reference', models.CharField(max_length=255, verbose_name='Referencia')),
                ('document', models.CharField(blank=True, max_length=120, verbose_name='Documento')),
                ('type_document', models.CharField(blank=True, choices=[('DNI', 'DNI'), ('CE', 'Carnet de extranjería')], max_length=120, verbose_name='Tipo Documento')),
                ('phone', models.CharField(max_length=120, verbose_name='Celular')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_ordershipping', to='order.Order')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.CustomerShippingAddress')),
                ('ubigeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubigeo_order_shipping_address', to='ubigeo.Ubigeo')),
            ],
            options={
                'verbose_name': 'OrderShipping',
                'verbose_name_plural': 'OrderShipping',
            },
        ),
        migrations.AlterUniqueTogether(
            name='orderdetail',
            unique_together=set([('order', 'productdetail')]),
        ),
    ]
