# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_status',
            field=models.CharField(blank=True, choices=[('PG', 'Pagado'), ('DN', 'Denegado'), ('RC', 'Rechazado'), ('PE', 'Pendiente'), ('PR_1', 'Proceso Paso 1'), ('PR_2', 'Proceso Paso 2'), ('DES', 'En Despacho'), ('CAM', 'En Camino'), ('COM', 'Completado'), ('CN', 'Cancelado')], max_length=255, verbose_name='type_status'),
        ),
        migrations.AlterField(
            model_name='ordercustomer',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ordercustomer',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='ordercustomer',
            name='phone',
            field=models.CharField(blank=True, max_length=120, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='ordershippingaddress',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ordershippingaddress',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='ordershippingaddress',
            name='reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='Referencia'),
        ),
    ]
