# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-07 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20180307_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Envio'),
        ),
    ]
