# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 02:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20180307_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
