# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-11 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type_status_shipping',
            field=models.CharField(choices=[('AL', 'En Almacén'), ('DS', 'En Despacho'), ('EG', 'Entregado')], default='AL', max_length=255, verbose_name='type status shipping'),
        ),
    ]
