# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20180319_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_status',
            field=models.CharField(blank=True, choices=[('PG', 'Pagado'), ('DN', 'Denegado'), ('RC', 'Rechazado'), ('PE', 'Pendiente'), ('PR_1', 'Pendiente'), ('CN', 'Cancelado')], max_length=255, verbose_name='type_status'),
        ),
    ]
