# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20180321_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_status',
            field=models.CharField(blank=True, choices=[('PR_1', 'Pendiente'), ('RC', 'Rechazado'), ('PG', 'Pagado'), ('RE', 'Reembolso')], max_length=255, verbose_name='type_status'),
        ),
    ]
