# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-28 13:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_discount_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_influencer',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
