# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('influencer', '0003_auto_20171228_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_trash', models.BooleanField(default=False, verbose_name='is trash')),
                ('sku', models.CharField(max_length=120, unique=True, verbose_name='sku')),
                ('stock', models.PositiveSmallIntegerField(verbose_name='stock')),
                ('price', models.PositiveSmallIntegerField(verbose_name='price')),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('meta_description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('name', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('is_variation', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(related_name='category_product_class', to='category.Category')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_product_class', to='influencer.Influencer')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_class_products', to='product.ProductClass'),
        ),
    ]
