# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_auto_20180120_1733'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='family',
            field=models.ManyToManyField(related_name='family_product_class', to='family.Family'),
        ),
    ]
