# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-10 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0004_auto_20180118_0651'),
        ('product', '0003_auto_20180127_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGaleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/%Y/%m/%d/')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'ProductGaleryImage',
                'verbose_name_plural': 'ProductGaleryImages',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=1, verbose_name='Position')),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ProductImages',
                'verbose_name_plural': 'ProductImagess',
            },
        ),
        migrations.AlterModelOptions(
            name='productattributevalue',
            options={'verbose_name': 'ProductAttributeValue', 'verbose_name_plural': 'ProductAttributeValues'},
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='attribute_product', to='attribute.Attribute'),
        ),
        migrations.AddField(
            model_name='productclass',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='productclass',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productclass',
            name='is_trash',
            field=models.BooleanField(default=False, verbose_name='is trash'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='stock'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_product_images', to='product.Product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='product_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_galery_images', to='product.ProductGaleryImage'),
        ),
        migrations.AddField(
            model_name='productgaleryimage',
            name='product_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_class_galery_images', to='product.ProductClass'),
        ),
    ]
