# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-10 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0004_auto_20180118_0651'),
        ('product', '0004_auto_20180210_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.AddField(
            model_name='product',
            name='attribute_option',
            field=models.ManyToManyField(blank=True, related_name='attribute_product_option', to='attribute.AttributeOption'),
        ),
    ]
