# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-10 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20180210_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productclass',
            old_name='family_fk',
            new_name='family',
        ),
    ]
