# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-10 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20180210_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_variation',
            field=models.BooleanField(default=False),
        ),
    ]
