# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 20:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20180227_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclass',
            name='data_sheet',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
