# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-31 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productclass_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclass',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_fk_product_class', to='family.Family'),
        ),
    ]
