# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-24 03:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0004_influencer_banner'),
        ('custom_auth', '0002_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfluencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_influencers', to='influencer.Influencer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_influencers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserInfluencer',
                'verbose_name_plural': 'UserInfluencers',
            },
        ),
    ]
