# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-24 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_userinfluencer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('ECOMMERCE', 'ECOMMERCE'), ('INFLUENCER', 'INFLUENCER')], max_length=120, verbose_name='type user'),
        ),
    ]
