# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-28 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_auto_20180423_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfluencer',
            name='influencer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_user_influencers', to='influencer.Influencer'),
        ),
    ]
