# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-28 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_auto_20180428_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfluencer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_user_influencer', to=settings.AUTH_USER_MODEL),
        ),
    ]
