# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_trash', models.BooleanField(default=False, verbose_name='is trash')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('name_store', models.CharField(max_length=255, verbose_name='Name Store')),
                ('is_use_search', models.BooleanField(default=False, verbose_name='Use in search')),
                ('type_name', models.CharField(choices=[('INPUT', 'Input'), ('TEXTAREA', 'Textarea'), ('BOOLEAN', 'SI / NO'), ('SELECT_SINGLE', 'Selección'), ('COLOUR', 'Color')], max_length=120, verbose_name='Type of attribute')),
                ('is_filter', models.BooleanField(default=False, verbose_name='Filtered')),
                ('is_variation', models.BooleanField(default=False, verbose_name='Variation')),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
            },
        ),
        migrations.CreateModel(
            name='AttributeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_trash', models.BooleanField(default=False, verbose_name='is trash')),
                ('position', models.IntegerField(default=1, verbose_name='Position')),
                ('option', models.CharField(max_length=255, verbose_name='Option')),
                ('slug', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Atributo',
                'verbose_name_plural': 'Atributos',
            },
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together=set([('name', 'type_name')]),
        ),
    ]
