# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 02:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeoption',
            name='attr',
            field=models.CharField(default='', max_length=255, verbose_name='Option'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attribute',
            name='type_name',
            field=models.CharField(choices=[('INPUT', 'Input'), ('TEXTAREA', 'Textarea'), ('BOOLEAN', 'SI / NO'), ('SELECT_SINGLE', 'Selección'), ('COLOUR', 'Color'), ('SELECT_MULTIPLE', 'Selección Multiple')], max_length=120, verbose_name='Type of attribute'),
        ),
    ]
