# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0002_auto_20180117_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeoption',
            name='attribute',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='attribute_options', to='attribute.Attribute'),
            preserve_default=False,
        ),
    ]
