# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0003_attributeoption_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeoption',
            name='attr',
            field=models.CharField(blank=True, max_length=255, verbose_name='attr'),
        ),
    ]
