# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0004_auto_20180118_0651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributeoption',
            options={'ordering': ['position'], 'verbose_name': 'Atributo', 'verbose_name_plural': 'Atributos'},
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name_store',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name Store'),
        ),
    ]
