# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('influencer', '0004_influencer_banner'),
        ('customers', '0014_auto_20180403_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('is_limit', models.BooleanField(default=False)),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Date Start')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Date End')),
                ('prefix', models.CharField(max_length=120, verbose_name='Prefix')),
                ('type_discount', models.CharField(choices=[('PTJ', 'Porcentaje (%)'), ('SLS', 'Soles')], max_length=60, verbose_name='Type Discount')),
                ('discount', models.FloatField(verbose_name='Discoubt')),
                ('quantity_customer', models.PositiveIntegerField(default=1, verbose_name='Use for Customer')),
                ('influencers', models.ManyToManyField(blank=True, related_name='influencer_coupons', to='influencer.Influencer')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='CouponGenerate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, unique=True, verbose_name='Code')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
                ('date_validated', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_generates', to='promotion.Coupon')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_coupon_generates', to='customers.Customer')),
            ],
            options={
                'verbose_name': 'CouponGenerate',
                'verbose_name_plural': 'CouponGenerates',
            },
        ),
    ]
