# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0002_auto_20180404_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_trash',
            field=models.BooleanField(default=False, verbose_name='is trash'),
        ),
        migrations.AddField(
            model_name='coupongenerate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='coupongenerate',
            name='is_trash',
            field=models.BooleanField(default=False, verbose_name='is trash'),
        ),
    ]
