# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-12 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0003_auto_20180404_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='prefix',
            field=models.CharField(max_length=120, unique=True, verbose_name='Prefix'),
        ),
    ]
