# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-12 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotion', '0004_auto_20180412_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='Stock'),
        ),
    ]
