# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20180323_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsbook',
            name='mount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
