# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20180323_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintsbook',
            name='consumers_order',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaintsbook',
            name='pedido',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
