# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20180323_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintsbook',
            name='observation',
            field=models.TextField(blank=True),
        ),
    ]
