# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_complaintsbook_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintsbook',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
