# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0002_auto_20171227_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerseo',
            name='influencer',
        ),
        migrations.RenameField(
            model_name='influencer',
            old_name='url',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='influencer',
            name='image',
            field=models.ImageField(upload_to='influencer/%Y/%m/%d', verbose_name='Photo'),
        ),
        migrations.DeleteModel(
            name='InfluencerSeo',
        ),
    ]
