# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-27 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencer', '0003_auto_20171228_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencer',
            name='banner',
            field=models.ImageField(default='', upload_to='influencer_banner/%Y/%m/%d', verbose_name='Banner'),
            preserve_default=False,
        ),
    ]
