# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-27 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_trash', models.BooleanField(default=False, verbose_name='is trash')),
                ('position', models.IntegerField(default=1, verbose_name='Position')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('banner', models.ImageField(upload_to='home_banner', verbose_name='Banner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
