# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_frequentquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
            ],
            options={
                'verbose_name_plural': 'TermsConditionss',
                'verbose_name': 'TermsConditions',
            },
        ),
        migrations.CreateModel(
            name='TermsConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
            ],
            options={
                'verbose_name_plural': 'TermsConditionss',
                'verbose_name': 'TermsConditions',
            },
        ),
        migrations.AlterModelOptions(
            name='frequentquestion',
            options={'verbose_name': 'FrequentQuestion', 'verbose_name_plural': 'FrequentQuestion'},
        ),
    ]
