# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='name',
            field=models.CharField(default='', max_length=120, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pages',
            name='title',
            field=models.CharField(max_length=120, verbose_name='title'),
        ),
    ]
