# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-07 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20180316_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
            ],
            options={
                'verbose_name_plural': 'FrequentQuestion',
                'verbose_name': 'FrequentQuestion',
            },
        ),
        migrations.RemoveField(
            model_name='frequentquestion',
            name='content',
        ),
        migrations.AddField(
            model_name='frequentquestion',
            name='question',
            field=models.CharField(default='', max_length=120, verbose_name='Question'),
            preserve_default=False,
        ),
    ]
