# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-07 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20180407_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentQuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('position', models.IntegerField(default=1, verbose_name='Position')),
                ('question', models.CharField(max_length=120, verbose_name='Question')),
                ('content', models.TextField(verbose_name='Content')),
            ],
            options={
                'verbose_name': 'FrequentQuestion',
                'verbose_name_plural': 'FrequentQuestion',
            },
        ),
        migrations.DeleteModel(
            name='FrequentQuestion',
        ),
        migrations.DeleteModel(
            name='FrequentResponse',
        ),
    ]
