# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-07 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20180407_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentquestionresponse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='frequentquestionresponse',
            name='is_trash',
            field=models.BooleanField(default=False, verbose_name='is trash'),
        ),
    ]
