# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-07 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20180407_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentquestionresponse',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='frequentquestionresponse',
            name='slug',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frequentquestionresponse',
            name='title',
            field=models.CharField(default='', max_length=120, verbose_name='title'),
            preserve_default=False,
        ),
    ]
