# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-19 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20180407_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='url',
            field=models.URLField(blank=True, verbose_name='Url'),
        ),
    ]
