# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubigeo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('ubigeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubigeo_shipping_costs', to='ubigeo.Ubigeo')),
            ],
            options={
                'verbose_name': 'ShippingPrice',
                'verbose_name_plural': 'ShippingPrices',
            },
        ),
    ]
