# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubigeo', '0001_initial'),
        ('customers', '0002_auto_20180303_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='Nombres')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Apellidos')),
                ('type_document', models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carnet de extranjería')], max_length=120, verbose_name='Type Document')),
                ('document', models.CharField(max_length=120, verbose_name='Document')),
                ('phone', models.CharField(max_length=120, verbose_name='Phone')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('reference', models.CharField(max_length=255, verbose_name='Referencia')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_shipping_address', to='customers.Customer')),
                ('ubigeo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zip_code_shipping_address', to='ubigeo.Ubigeo')),
            ],
            options={
                'verbose_name': 'ShippingAddress',
                'verbose_name_plural': 'ShippingAddress',
            },
        ),
    ]
