# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customershippingaddress_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_send_email',
            field=models.BooleanField(default=False),
        ),
    ]
