# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 03:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20180308_1536'),
        ('customers', '0006_auto_20180313_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProductFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_favorites', to='customers.Customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_customer_favorites', to='product.Product')),
            ],
            options={
                'verbose_name_plural': 'CustomerProductFavorites',
                'verbose_name': 'CustomerProductFavorite',
            },
        ),
    ]
