# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customerproductfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproductfavorite',
            name='code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
