# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_customerproductfavorite_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerproductfavorite',
            name='product',
        ),
    ]
