# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customerproductfavorite_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproductfavorite',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_favorites', to='customers.Customer'),
        ),
    ]
