# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20180308_1536'),
        ('customers', '0011_auto_20180403_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerproductfavorite',
            name='products',
        ),
        migrations.AddField(
            model_name='customerproductfavorite',
            name='product_class',
            field=models.ManyToManyField(related_name='product_customer_favorites', to='product.ProductClass'),
        ),
    ]
