# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_auto_20180403_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproductfavorite',
            name='code',
            field=models.UUIDField(default=uuid.UUID('91b30bb0-77c0-4490-aa74-66515fc4deff'), editable=False),
        ),
    ]
