# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_customershippingaddress_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customershippingaddress',
            name='order',
        ),
        migrations.RemoveField(
            model_name='customershippingaddress',
            name='title',
        ),
    ]
