# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 15:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0012_productclass_data_sheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(max_length=120, unique=True, verbose_name='Cart Code')),
                ('status', models.CharField(choices=[('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('CHECKOUT', 'Checkout'), ('ORDER', 'Order')], max_length=120, verbose_name='Status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'MODELNAMEs',
                'verbose_name': 'MODELNAME',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='cart.Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cart_items', to='product.Product')),
            ],
            options={
                'verbose_name_plural': 'CartItems',
                'verbose_name': 'CartItem',
            },
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set([('product', 'cart')]),
        ),
    ]
