# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-18 02:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20180227_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={'msj': '', 'status': ''}),
        ),
    ]
