# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-18 02:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='cart',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}),
        ),
    ]
