# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-26 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20180417_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('id',), 'verbose_name': 'CartItem', 'verbose_name_plural': 'CartItems'},
        ),
    ]
