# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_auto_20180118_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='familygroup',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='familygroupattribute',
            name='position',
            field=models.IntegerField(default=1, verbose_name='Position'),
        ),
    ]
