# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0003_auto_20180120_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='familygroupattribute',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_familygroupatribute', to='family.Family'),
        ),
    ]
