# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0005_auto_20180215_1603'),
        ('family', '0004_familygroupattribute_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_trash', models.BooleanField(default=False, verbose_name='is trash')),
                ('position', models.IntegerField(default=1, verbose_name='Position')),
                ('is_required', models.BooleanField(default=False, verbose_name='Obligatorio')),
                ('atribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_familygroupatribute', to='attribute.Attribute')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_familygroupatribute', to='family.Family')),
            ],
            options={
                'verbose_name': 'Family Group Atribute',
                'verbose_name_plural': 'Family Group Atribute',
            },
        ),
        migrations.RemoveField(
            model_name='familygroupattribute',
            name='atribute',
        ),
        migrations.RemoveField(
            model_name='familygroupattribute',
            name='family',
        ),
        migrations.RemoveField(
            model_name='familygroupattribute',
            name='family_group',
        ),
        migrations.DeleteModel(
            name='FamilyGroupAttribute',
        ),
    ]
