# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0005_auto_20180215_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familyattribute',
            old_name='atribute',
            new_name='attribute',
        ),
    ]
