# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_auto_20180215_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyattribute',
            name='attribute',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='attribute_familygroupatribute', to='attribute.Attribute'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familyattribute',
            name='family',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='family_familygroupatribute', to='family.Family'),
            preserve_default=False,
        ),
    ]
