# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_dep', models.CharField(blank=True, db_index=True, max_length=2, null=True, verbose_name='Código')),
                ('desc_dep', models.CharField(blank=True, max_length=13, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_prov', models.CharField(blank=True, db_index=True, max_length=4, null=True, verbose_name='Código')),
                ('desc_prov', models.CharField(blank=True, max_length=25, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('cod_dep_inei', models.CharField(blank=True, max_length=2, null=True)),
                ('desc_dep_inei', models.CharField(blank=True, max_length=13, null=True)),
                ('cod_prov_inei', models.CharField(blank=True, max_length=4, null=True)),
                ('desc_prov_inei', models.CharField(blank=True, max_length=25, null=True)),
                ('cod_ubigeo_inei', models.CharField(db_index=True, max_length=6, primary_key=True, serialize=False)),
                ('desc_ubigeo_inei', models.CharField(blank=True, max_length=36, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ubigeo',
                'verbose_name': 'Ubigeo',
            },
        ),
    ]
